
INSERT INTO public.trekking_routes (country_id, region_id, name, slug, short_description, description, difficulty, duration_days, distance_km, elevation_max_m, best_season, start_location, end_location, estimated_cost_min, estimated_cost_max, hero_image, permits, accommodation, food, transportation, safety, is_featured)
SELECT c.id, r.id, v.name, v.slug, v.short, v.descr, v.diff, v.dur, v.dist, v.elev, v.season, v.startl, v.endl, v.cmin, v.cmax, v.img, v.permits, v.acc, v.food, v.trans, v.safety, v.feat
FROM public.countries c
JOIN public.regions r ON r.country_id = c.id
JOIN (VALUES
('everest','Everest Base Camp Trek','everest-base-camp-trek','The classic walk to the foot of Everest through Namche, Tengboche and the Khumbu glacier.','Nepal''s signature trek. A mountain flight to Lukla drops you into the Dudh Koshi valley; from there the trail climbs through Sherpa villages, pine forest and finally glacial moraine to Everest Base Camp at 5,364 m, with a sunrise climb of Kala Patthar for the best view of Everest itself.','Challenging','12-14 days',130,5545,'Spring (Mar-May) / Autumn (Sep-Nov)','Kathmandu','Everest Base Camp',1100,2200,'/images/everest.jpg','Sagarmatha National Park entry + Khumbu Pasang Lhamu Rural Municipality permit','Teahouses/lodges every few hours; twin rooms, shared bathrooms higher up','Dal bhat, noodles, soups and bakery items; costs rise with altitude','Flight Kathmandu-Lukla (approx. 35 min) or drive to Ramechhap in peak season','Two acclimatisation days are standard. Ascend no more than 400-500 m sleeping altitude per day above 3,000 m.',true),
('everest','Gokyo Lakes Trek','gokyo-lakes-trek','Turquoise glacial lakes and the Gokyo Ri panorama, quieter than the main EBC trail.','A parallel Khumbu route up the Dudh Koshi to a chain of six turquoise lakes beside the Ngozumpa glacier. Gokyo Ri (5,357 m) gives a four-8000er panorama - Everest, Lhotse, Makalu and Cho Oyu - in one sweep.','Challenging','12-13 days',110,5357,'Spring / Autumn','Kathmandu','Gokyo',1000,2000,'/images/everest.jpg','Sagarmatha National Park + local rural municipality permit','Teahouses in Dole, Machhermo and Gokyo','Lodge menus; limited choice above Machhermo','Flight to Lukla, then on foot','Machhermo has a rescue post and daily altitude talk.',true),
('everest','Gokyo to Everest Base Camp via Cho La','gokyo-everest-base-camp-route','Links the Gokyo lakes to Base Camp over the glaciated Cho La pass.','Combines both Khumbu highlights into one loop, crossing the 5,420 m Cho La between Thagnak and Dzongla. Crampons or microspikes are useful in early spring.','Strenuous','16-18 days',160,5545,'Spring / Autumn','Kathmandu','Lukla',1400,2600,'/images/everest.jpg','Sagarmatha National Park + rural municipality permit','Teahouses; none on the pass itself','Lodge food; carry snacks for the pass day','Flight to Lukla','Do not cross Cho La alone or in fresh snow.',false),
('everest','Everest Three Passes Trek','three-passes-trek','Renjo La, Cho La and Kongma La in one high circuit of the Khumbu.','The most complete Khumbu itinerary: three passes above 5,300 m plus Gokyo Ri, Kala Patthar and Chhukhung Ri. Long days, real altitude and a strong sense of remoteness between passes.','Strenuous','18-21 days',166,5545,'Spring / Autumn','Kathmandu','Lukla',1600,3000,'/images/everest.jpg','Sagarmatha National Park + rural municipality permit','Teahouses throughout, basic on pass approaches','Lodge food; stock snacks in Namche','Flight to Lukla','Requires prior high-altitude experience and a flexible schedule for weather.',false),
('everest','Everest View Trek','everest-view-trek','A short Khumbu taster to Namche and the Everest View Hotel ridge.','For trekkers short on time: Lukla, Phakding, Namche Bazaar and the Syangboche ridge, where Everest, Ama Dablam and Thamserku line the skyline. No extreme altitude.','Moderate','7-8 days',45,3880,'Spring / Autumn','Kathmandu','Namche Bazaar',650,1100,'/images/everest.jpg','Sagarmatha National Park + rural municipality permit','Comfortable lodges in Namche','Wide menus including bakeries and coffee','Flight to Lukla','Still involves 3,800 m - take the Namche rest day.',false),
('annapurna','Annapurna Circuit Trek','annapurna-circuit-trek','Around the Annapurna massif over Thorong La, from paddy fields to Tibetan desert.','A classic long-distance trek that circles the Annapurna range, climbing the Marsyangdi valley to Manang, crossing Thorong La (5,416 m) and descending to Muktinath and the Kali Gandaki. Road access now lets you shorten either end.','Challenging','12-16 days',160,5416,'Spring / Autumn','Besisahar','Jomsom',900,1800,'/images/annapurna.jpg','ACAP entry permit + TIMS card','Teahouses the whole way, some with private bathrooms','Excellent variety; apple products in Marpha','Jeep or bus Kathmandu-Besisahar; flight or jeep out of Jomsom','Manang rest day is essential before Thorong La; cross the pass early.',true),
('annapurna','Annapurna Base Camp Trek','annapurna-base-camp-trek','Into the Annapurna Sanctuary, an amphitheatre ringed by 7,000 m walls.','From Pokhara the trail climbs through Gurung villages and rhododendron forest into a hidden glacial basin at 4,130 m, encircled by Annapurna I, Hiunchuli and Machhapuchhre.','Moderate','7-11 days',110,4130,'Spring / Autumn','Pokhara','Annapurna Base Camp',600,1200,'/images/annapurna.jpg','ACAP entry permit + TIMS card','Dense teahouse network','Good food throughout, including the sanctuary','Drive Pokhara to Nayapul/Jhinu (approx. 2 hours)','Avalanche risk in the sanctuary approach after heavy snow; check conditions in winter.',true),
('annapurna','Mardi Himal Trek','mardi-himal-trek','A short ridge trek with close-up Machhapuchhre views.','A high ridge route above the Modi Khola, opened for teahouse trekking relatively recently. Forest camp, low camp and high camp lead to a viewpoint at 4,500 m below the fishtail summit.','Moderate','5-7 days',45,4500,'Spring / Autumn','Pokhara','Mardi Himal Base Camp',350,700,'/images/annapurna.jpg','ACAP entry permit + TIMS card','Small ridge-top lodges; book ahead in season','Simple menus, limited at High Camp','Drive Pokhara to Kande (approx. 1 hour)','The upper ridge is exposed in wind and cloud; start early.',true),
('annapurna','Ghorepani Poon Hill Trek','ghorepani-poon-hill-trek','The best short sunrise trek in Nepal, through Magar villages and rhododendron forest.','Stone staircases climb from the Modi Khola to Ghorepani, then a pre-dawn walk to Poon Hill (3,210 m) for sunrise over Dhaulagiri and Annapurna South.','Easy','4-5 days',40,3210,'Year-round, best Mar-Apr for blooms','Pokhara','Ghandruk',250,500,'/images/annapurna.jpg','ACAP entry permit + TIMS card','Comfortable lodges, some with hot showers','Very good; Ghorepani has bakeries','Drive Pokhara to Nayapul (approx. 1.5 hours)','Low altitude and low risk; stairs are the main challenge.',false),
('annapurna','Khopra Ridge Trek','khopra-ridge-trek','A quiet community-lodge ridge with Dhaulagiri face-on.','An alternative to Poon Hill using community-run lodges along the Khopra Danda ridge, with an optional side trip to the sacred Kaire Lake at 4,660 m.','Moderate','7-9 days',60,4660,'Spring / Autumn','Pokhara','Khopra Danda',450,850,'/images/annapurna.jpg','ACAP entry permit + TIMS card','Community lodges; fewer facilities than main trails','Simple, mostly dal bhat','Drive Pokhara to Nayapul','Kaire Lake day is a long high push - go with a guide.',false),
('annapurna','Tilicho Lake Trek','tilicho-lake-trek','A side route from Manang to one of the highest large lakes in the world.','From Manang the trail crosses landslide-prone slopes to Tilicho Base Camp and then climbs to the lake at 4,919 m. Often combined with the Annapurna Circuit.','Challenging','14-16 days',150,5416,'Spring / Autumn','Besisahar','Jomsom',1000,1900,'/images/annapurna.jpg','ACAP entry permit + TIMS card','Teahouses; Tilicho Base Camp is basic and fills up','Dal bhat and noodles; limited at base camp','Jeep Kathmandu-Besisahar or Chame','The scree traverse to base camp is exposed - avoid in rain.',true),
('annapurna','Nar Phu Valley Trek','nar-phu-valley-trek','Restricted medieval villages behind the Annapurna range.','A permit-restricted side valley of walled Tibetan villages, sky caves and the Kang La pass (5,320 m) back to Manang.','Strenuous','14-17 days',105,5320,'Spring / Autumn','Koto','Manang',1400,2400,'/images/annapurna.jpg','Restricted Area Permit (guide + 2 trekkers minimum) + ACAP','Basic lodges and homestays in Nar and Phu','Limited menus; carry supplements','Jeep Kathmandu-Koto via Besisahar','Restricted area - a licensed guide is legally required.',false),
('langtang','Langtang Valley Trek','langtang-valley-trek','A glacier-headed valley a day''s drive from Kathmandu, rebuilt after 2015.','The Langtang Khola climbs from forest into a wide yak-grazing valley below Langtang Lirung. Kyanjin Gompa is the base for Tserko Ri (4,984 m) and the cheese factory.','Moderate','7-9 days',65,4984,'Spring / Autumn','Syabrubesi','Kyanjin Gompa',450,900,'/images/langtang.jpg','Langtang National Park entry + TIMS card','Rebuilt teahouses throughout the valley','Good; local yak cheese and bakeries at Kyanjin','Bus or jeep Kathmandu-Syabrubesi (approx. 7 hours)','Tserko Ri is a 1,000 m day climb - acclimatise at Kyanjin first.',true),
('langtang','Gosaikunda Trek','gosaikunda-trek','Sacred high-altitude lakes above the Langtang foothills.','A pilgrimage route to a cluster of alpine lakes at 4,380 m, sacred to both Hindus and Buddhists and busiest at the Janai Purnima full moon.','Moderate','5-7 days',55,4610,'Spring / Autumn','Dhunche','Gosaikunda',400,800,'/images/langtang.jpg','Langtang National Park entry + TIMS card','Teahouses at Sing Gompa, Lauribina and the lakes','Simple food; no meat at the lakes','Bus or jeep Kathmandu-Dhunche (approx. 6 hours)','Rapid ascent from Dhunche - build in a night at Sing Gompa.',true),
('langtang','Langtang - Gosaikunda Combined','langtang-gosaikunda-trek','Valley trek plus the sacred lakes over the Lauribina La.','Walks the Langtang valley, then crosses back south over Lauribina La (4,610 m) to Gosaikunda and out via Helambu or Dhunche.','Challenging','12-14 days',120,4984,'Spring / Autumn','Syabrubesi','Dhunche',750,1400,'/images/langtang.jpg','Langtang National Park entry + TIMS card','Teahouses; sparse between Kyanjin and Gosaikunda','Basic on the crossing days','Bus or jeep to Syabrubesi','Lauribina La holds snow into April.',false),
('langtang','Helambu Trek','helambu-trek','A gentle Sherpa and Tamang village circuit close to Kathmandu.','Low-altitude ridge walking north of Kathmandu through Sherpa villages, terraced hills and forest - a good cool-season or short-window option.','Easy','5-7 days',60,3650,'Autumn / Winter / Spring','Sundarijal','Melamchi',300,600,'/images/langtang.jpg','Langtang National Park entry + TIMS card','Village lodges and homestays','Home-cooked Nepali food','Local bus or taxi from Kathmandu to Sundarijal','Low risk; carry a torch for early starts.',false),
('manaslu','Manaslu Circuit Trek','manaslu-circuit-trek','A wilder circuit around the eighth-highest mountain, over Larke La.','The Budhi Gandaki gorge climbs from subtropical valley to Tibetan-influenced Samagaun, then crosses Larke La (5,106 m) into the Annapurna region. Restricted permits keep crowds low.','Strenuous','14-16 days',177,5106,'Spring / Autumn','Soti Khola / Machha Khola','Dharapani',1200,2200,'/images/annapurna.jpg','Manaslu Restricted Area Permit + MCAP + ACAP; guide and 2 trekkers minimum','Teahouses the whole route, simpler than Annapurna','Dal bhat dominant; limited choice past Namrung','Jeep Kathmandu-Machha Khola (approx. 8-9 hours)','Larke La is long and cold - start before 04:00 and turn back in storms.',true),
('manaslu','Tsum Valley Trek','tsum-valley-trek','A hidden Buddhist valley of gompas and mani walls.','A restricted side valley off the Manaslu route, culturally Tibetan, with Mu Gompa and Rachen Gompa at its head. Often combined with the Manaslu Circuit.','Challenging','14-18 days',150,3700,'Spring / Autumn','Machha Khola','Mu Gompa',1200,2100,'/images/annapurna.jpg','Tsum Valley Restricted Area Permit + MCAP','Homestays and small lodges','Simple vegetarian food in the upper valley','Jeep Kathmandu-Machha Khola','Guide legally required; the valley is a non-violence zone - respect local customs.',false),
('manaslu','Ganesh Himal Trek','ganesh-himal-trek','Low-traffic ridges and hot springs between Langtang and Manaslu.','A community-tourism route through Tamang villages with views of Ganesh Himal and Manaslu, and the Tatopani hot springs.','Moderate','9-12 days',95,4100,'Autumn / Spring','Syabrubesi','Arughat',600,1100,'/images/langtang.jpg','TIMS card; local area permits where applicable','Homestays, few commercial lodges','Local home cooking','Bus or jeep from Kathmandu','Trails are less marked - a guide is recommended.',false),
('mustang','Upper Mustang Trek','upper-mustang-trek','The walled city of Lo Manthang and the former Kingdom of Lo.','North of the Himalaya in the rain shadow, Upper Mustang is an arid Tibetan plateau of sky caves, red cliffs and whitewashed monasteries, culminating at the walled capital Lo Manthang (3,840 m).','Moderate','10-14 days',115,4230,'Mar-Nov, including monsoon','Jomsom','Lo Manthang',1800,3000,'/images/mustang.jpg','Upper Mustang Restricted Area Permit (USD 500 for 10 days) + ACAP','Simple lodges and guesthouses in each village','Tibetan bread, thukpa, dal bhat','Flight Pokhara-Jomsom (approx. 20 min) or jeep','Strong afternoon winds in the Kali Gandaki - walk mornings.',true),
('mustang','Lower Mustang Trek','lower-mustang-trek','Kagbeni, Marpha and the Kali Gandaki without a restricted permit.','Apple orchards, Thakali villages and the world''s deepest gorge between Dhaulagiri and Annapurna, walkable year-round from Jomsom.','Easy','5-7 days',50,3800,'Year-round','Jomsom','Muktinath',400,800,'/images/mustang.jpg','ACAP entry permit + TIMS card','Comfortable Thakali-run lodges','Excellent Thakali dal bhat and apple brandy','Flight Pokhara-Jomsom or jeep from Beni','Windy afternoons; road dust on jeep sections.',false),
('mustang','Jomsom - Muktinath Route','jomsom-muktinath-route','A short pilgrimage route to the 108 water spouts of Muktinath.','A walk or jeep ride up the Kali Gandaki from Jomsom through Kagbeni to Muktinath (3,760 m), sacred to Hindus and Buddhists alike.','Easy','3-4 days',22,3760,'Year-round','Jomsom','Muktinath',200,450,'/images/mustang.jpg','ACAP entry permit + TIMS card','Lodges in Kagbeni, Jharkot and Ranipauwa','Good Thakali food','Flight Pokhara-Jomsom; jeeps run the whole route','Cold nights at Muktinath in winter.',false),
('dolpo','Upper Dolpo Trek','upper-dolpo-trek','A long expedition-style crossing of Nepal''s remotest high plateau.','Weeks of walking over 5,000 m passes between Shey Phoksundo, Shey Gompa and the Tibetan-culture villages of Saldang and Tinje. Mostly camping.','Strenuous','21-26 days',250,5360,'Jun-Sep (rain shadow)','Juphal','Juphal',3000,4500,'/images/mustang.jpg','Upper Dolpo Restricted Area Permit (USD 500 per 10 days) + Shey Phoksundo National Park','Full camping support; occasional village homestays','Expedition catering; resupply is very limited','Flight Kathmandu-Nepalgunj-Juphal','Full logistics support and a licensed guide are mandatory.',false),
('dolpo','Lower Dolpo Trek','lower-dolpo-trek','Shey Phoksundo Lake and the Numa La / Baga La passes.','A shorter Dolpo itinerary reaching Nepal''s deepest lake and crossing two passes above 5,000 m through Bon and Buddhist villages.','Strenuous','16-18 days',180,5190,'May-Oct','Juphal','Juphal',2000,3200,'/images/mustang.jpg','Lower Dolpo Restricted Area Permit + Shey Phoksundo National Park','Mostly camping with limited teahouses','Camp catering','Flight Kathmandu-Nepalgunj-Juphal','Remote with no road evacuation - insurance with helicopter cover is essential.',false),
('dolpo','Shey Phoksundo Lake Route','shey-phoksundo-route','A shorter walk in to Nepal''s deepest and bluest lake.','From the Juphal airstrip the trail follows the Suli Gad river to Ringmo village and the 145 m-deep turquoise lake at 3,611 m.','Moderate','9-11 days',85,4040,'May-Oct','Juphal','Ringmo',1200,1900,'/images/mustang.jpg','Shey Phoksundo National Park + Lower Dolpo permit','Basic lodges and homestays in Ringmo','Simple local food','Flight Kathmandu-Nepalgunj-Juphal','Flights to Juphal are weather-dependent; keep buffer days.',false),
('kanchenjunga','Kanchenjunga Base Camp Trek','kanchenjunga-base-camp-trek','Far-east wilderness beneath the world''s third-highest mountain.','A long approach through Limbu and Rai villages to both the north (Pangpema, 5,143 m) and south (Oktang) base camps of Kanchenjunga, with almost no other trekkers.','Strenuous','20-24 days',220,5143,'Spring / Autumn','Taplejung','Taplejung',1800,3000,'/images/langtang.jpg','Kanchenjunga Restricted Area Permit + KCAP; guide required','Basic teahouses and homestays','Mostly dal bhat; carry supplements high up','Flight Kathmandu-Bhadrapur then jeep to Taplejung (approx. 8 hours)','Very remote - carry a comprehensive first-aid kit and satellite communication.',false)
) AS v(region_slug, name, slug, short, descr, diff, dur, dist, elev, season, startl, endl, cmin, cmax, img, permits, acc, food, trans, safety, feat)
ON v.region_slug = r.slug
WHERE c.slug = 'nepal';
